[package]
name = "neocel"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
crossterm = "0.29.0"
csv = "1.4.0"
pyo3 = "0.27.2"
serde_json = "1.0.148"
uuid = {version = "1.19.0", features = ["v4", "serde"]}
